# Generated by Django 3.1.4 on 2021-01-03 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=64),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('Broomsticks', 'Broomsticks'), ('Category 1', 'Category 1'), ('Category 2', 'Category 2'), ('Category 3', 'Category 3'), ('Category 4', 'Category 4'), ('Category 5', 'Category 5'), ('Category 6', 'Category 6'), ('Category 7', 'Category 7'), ('Category 8', 'Category 8')], max_length=128)),
                ('starting', models.DecimalField(decimal_places=2, max_digits=9)),
                ('description', models.CharField(blank=True, max_length=4096)),
                ('photo', models.ImageField(upload_to='item_photo')),
                ('is_closed', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(blank=True, default=None, null=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=4096)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='auctions.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.FloatField()),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidder', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bidded_item', to='auctions.item')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='addit_photo')),
                ('item', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='auctions.item')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='items', to='auctions.Item'),
        ),
    ]
