# Generated by Django 3.1.4 on 2021-01-06 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_comment_date_posted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdditionalPhoto',
        ),
    ]
